### ISSUE TITLE
 Service 'ehsm_base' failed to build with error:  returned a non-zero code: 100

### ISSUE THREAD

**Issue by 20160920** [intel/ehsm#133]
Hi, I pull the ehsm and run docker-compose build, but always truck into the step of build ehsm_base image.Could you help me have a look?

**Comment by HawieLong** [comment]
Looks like your network has some problem connecting to apt-get source.
Can you change your apt-get source to a mirror address which you can reach out and try again?
Or you can provide more info like your commands and apt-get update info for us to further debugging

**Comment by 20160920** [comment]
我使用的是这个配置，不知道是否会自动渲染？ 尝试改version成0.2.1也还是不行😂
![Uploading image.png…]()

**Comment by 20160920** [comment]
![image](https://user-images.githubusercontent.com/40284225/175921029-83042eb0-9d7c-48d1-bc4b-506e7bd82be9.png)
change the proxy but still don't work

**Comment by 20160920** [comment]
![image](https://user-images.githubusercontent.com/40284225/175924079-bd51357e-291b-48d9-97dc-dbd4ddd80755.png)
change apt-get source but still don't work

**Comment by yang8621** [comment]
![image](https://user-images.githubusercontent.com/34729487/175944159-8f362829-c752-4693-9c3b-5a18cb6a8026.png)
They are not valid proxies.
Does your env really require a proxy? if not, you could try to unset the proxy or delete it from the file.

**Comment by 20160920** [comment]
I delete the proxy.
![image](https://user-images.githubusercontent.com/40284225/176078388-1a25950b-b737-44dd-9478-a3594de036a4.png)
But still failed in this step.
![image](https://user-images.githubusercontent.com/40284225/176078536-e3abdfb3-350b-4f8b-870e-39960488212a.png)
change source but not work.
![image](https://user-images.githubusercontent.com/40284225/176078657-d3e3ca9f-fa1b-4abe-97f9-5a665fc9bae6.png)
Maybe I need set DNS of this image?

**Comment by 20160920** [comment]
this is my apt-get source, corresponding to the version of Ubuntu 18.04.
![image](https://user-images.githubusercontent.com/40284225/176107688-8605f978-9e38-4ce0-a7df-85f006936b69.png)
But it still don't work

**Comment by 20160920** [comment]
> Reference in new iss

I deleted proxy.👀

**Comment by 20160920** [comment]
So, is ehsm  there a solution to install in centos ? 😢

**Comment by 20160920** [comment]
1
