### ISSUE TITLE
How to use EHSM to encrypt a secret data? Is there any relevant document？

### ISSUE THREAD

**Issue by 20160920** [intel/ehsm#136]
If I need to enable secret data encryption like KMS，

**Comment by yang8621** [comment]
currently, you can refer to: https://github.com/intel/ehsm/blob/main/test/test_kms_with_cli.py#L111
secret manager with DB storage is under development now.  Thanks.

**Comment by grissomsh** [comment]
@yang8621 Could Kubernetes use eHSM as a KMS provider to encrypt secret data?

**Comment by yang8621** [comment]
Yes, of course. Common restful interfaces are provided to use.
