### ISSUE TITLE
the dkeycache service CPU usage is alawys 100% 

### ISSUE THREAD

**Issue by guolanting** [intel/ehsm#218]
when I deployed `ehsm` based on `https://github.com/intel/ehsm/tree/main/docker` , the dkeycache CPU usage is always 100%. 

![image](https://user-images.githubusercontent.com/62043931/208022956-f4606130-ee39-4e1f-8aec-6d6a995319ee.png)

`docker-compose logs`:
![image](https://user-images.githubusercontent.com/62043931/208023064-93423c0b-c09b-4008-9f87-90f694f11da3.png)

**Comment by syan10** [comment]
Thanks for the information, we will take a look at this.

**Comment by syan10** [comment]
hi,
The fix has already been merged, please try it again. Thanks.
