### ISSUE TITLE
Bug: memory leak

### ISSUE THREAD

**Issue by nntp4** [intel/ehsm#255]
memory leak happened in import_struct_from_json() function.
https://github.com/intel/ehsm/blob/a415147cf2152a29c5131b3a3cab849befee7513/core/App/ffi_operation.cpp#L92-L106
at lines 103 to 105, out_data is allocated but not free.

**Comment by yang8621** [comment]
Thanks.  Fixed. 
BTW, you can submit patches directly if you are interested.
