### ISSUE TITLE
Trouble with setting environment of quick start

### ISSUE THREAD

**Issue by ksy980418** [intel/ehsm#271]
I'm trying to install ehsm and quick start with the below document.

https://github.com/intel/ehsm/blob/main/docs/build-instructions.md

However, I faced some troubles with setting PCCS server IP and host ip.

Am I correct that we should change the pccs url in /etc/sgx_default_qcnl.conf with https://1.2.3.4:8081/sgx/certification/v3/  and host ip and pccs url in docker/.env?

For me, it doesn't work. May I get some help?

**Comment by yang8621** [comment]
Yes.  If you don't want to config pccs, you can run run_with_single.sh directly for test purpose.

**Comment by yang8621** [comment]
> Yes. If you don't want to config pccs, you can run run_with_single.sh directly for test purpose.

Before run run_with_single.sh, you need to manually install the dependencies described in build-instructions.md.

**Comment by ksy980418** [comment]
Thank you for the answer.

I tried to install the dependencies described in build-instructions.md and run run_with_single.sh but I met below errors.
And I can't find the reason why the error occurs.

ehsm clean build done.
ehsm libehsmprovider and libenclave-ehsm-core copied.

> ref-napi@3.0.3 install /home/ksy980418/ehsm/ehsm_kms_service/node_modules/ref-napi
> node-gyp-build

Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.15.0-67-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ksy980418/ehsm/ehsm_kms_service/node_modules/ref-napi
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN ehsm_kms_service@1.0.0 No repository field.
npm WARN ehsm_kms_service@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref-napi@3.0.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref-napi@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-08T12_27_11_302Z-debug.log
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'ffi-napi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ksy980418/ehsm/ehsm_kms_service/ehsm_napi.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by yang8621** [comment]
Seems your node modules are not successfully installed. You can check ehsm_kms_service/node_modules: 
ehsm_kms_service/node_modules$ ll | wc -l
108
there should be 100+ modules, including ffi-napi/.

You can try to remove node_modules and manually install by "npm install" under ehsm_kms_service.

**Comment by ksy980418** [comment]
Sorry for confusion.
I found that the first error was not by the npm.
It was by sgx sdk or psw like below.
But I already installed all required written in build-instructions.md.
Do I need to install additionally?

Please follow the instruction at https://github.com/intel/linux-sgx/blob/master/README.md#build-the-intelr-sgx-sdk-and-intelr-sgx-psw-package to install "mitigation tools" first.
make[1]: *** [Makefile:42: sgxssl] Error 1
make[1]: Leaving directory '/home/ksy980418/ehsm/third_party/intel-sgx-ssl/Linux'
make: *** [Makefile:63: ssl] Error 1

**Comment by yang8621** [comment]
Have you done the steps:
wget https://download.01.org/intel-sgx/sgx-linux/2.18/as.ld.objdump.r4.tar.gz
tar -zxf as.ld.objdump.r4.tar.gz
sudo cp external/toolset/{current_distr}/* /usr/local/bin

**Comment by ksy980418** [comment]
yes

~$ ls /usr/local/bin
ar              node-gyp  pip3.10        verilator_bin_dbg
as              objcopy   pip3.8         verilator_coverage
docker-compose  objdump   ranlib         verilator_coverage_bin_dbg
ld              pip       verilator      verilator_gantt
n               pip3      verilator_bin  verilator_profcfunc

**Comment by yang8621** [comment]
is /usr/local/bin in env var?
can "which objdump" be found?

**Comment by ksy980418** [comment]
yes it answers /usr/local/bin/objdump correctly.

**Comment by yang8621** [comment]
I would suggest trying to build it directly: https://github.com/intel/intel-sgx-ssl

**Comment by ksy980418** [comment]
It was gcc version problem. Thanks.

Sorry but I met other error...

Is this also some sgx setting error?

In file included from App/ehsm_provider.cpp:55:
/usr/include/sgx_dcap_quoteverify.h:206:11: error: ‘tdx_ql_qv_collateral_t’ does not name a type; did you mean ‘tdx_ql_qve_collateral_t’?
  206 |     const tdx_ql_qv_collateral_t *p_quote_collateral,
      |           ^~~~~~~~~~~~~~~~~~~~~~
      |           tdx_ql_qve_collateral_t
make[1]: *** [Makefile:181: App/ehsm_provider.o] Error 1
make[1]: Leaving directory '/home/ksy980418/ehsm/core'
make: *** [Makefile:41: all] Error 1

**Comment by yang8621** [comment]
How did you install the required sgx libraries?  What's sgx sdk version you installed? 

WORKDIR /opt/intel
RUN wget https://download.01.org/intel-sgx/sgx-dcap/1.15/linux/distro/ubuntu20.04-server/sgx_linux_x64_sdk_2.18.100.3.bin \
    && chmod 777 sgx_linux_x64_sdk_2.18.100.3.bin \
    && sh -c 'echo yes | ./sgx_linux_x64_sdk_2.18.100.3.bin'

#Install SDK toolset
RUN wget https://download.01.org/intel-sgx/sgx-linux/2.18/as.ld.objdump.r4.tar.gz \
    && tar -zxf as.ld.objdump.r4.tar.gz \
    && cp external/toolset/ubuntu20.04/* /usr/local/bin

# Install DCAP packages
# DCAP repository setup
RUN wget https://download.01.org/intel-sgx/sgx-dcap/1.15/linux/distro/ubuntu20.04-server/sgx_debian_local_repo.tgz \
    && tar xzf sgx_debian_local_repo.tgz \
    && echo 'deb [trusted=yes arch=amd64] file:///opt/intel/sgx_debian_local_repo focal main' | tee /etc/apt/sources.list.d/intel-sgx.list \
    && wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add - \
    && apt-get update

**Comment by ksy980418** [comment]
I just followed written in Build-Instructions page.

And I additionally installed sgx sdk 2.20 version.

But version 2.18 & 2.20 both don't work for me.

**Comment by ksy980418** [comment]
Thank you for your help.
I successfully execute run_with_single.sh.
I think it was some node.js version issues.
I erased node.js package and  the node module folder and reinstall, then it solved.

Thanks

**Comment by yang8621** [comment]
Glad to know it. 👍
